compiler: ghc-8.0.1
compiler-check: match-exact

resolver: lts-7.1

packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/haskoin.git
    commit: ddb3adbf59aa5a21c349e5db27ee977282036868
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
- location:
    git: https://github.com/runeksvendsen/haskell-rbpcp-api.git
    commit: f39757a183eac18f0c5dca25ac5032ec05f3feee
  extra-dep: true


# Haskoin dependencies
extra-deps:
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6

