resolver: lts-7.1

compiler: ghc-8.0.1
compiler-check: match-exact

packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/haskoin.git
    commit: 9add83fd4aa8bc960a15a1d24e6e831981a9f8a4
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
- location:
    git: https://github.com/runeksvendsen/rbpcp-api.git
    commit: 2b05a6aff8d5565b9fec8a307d2c0f75b90653ea
  extra-dep: true


# Haskoin dependencies
extra-deps:
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6

