resolver: lts-5.2

packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 7ccccb0a35ad959e4fcef91748c9d3653e39cb2e # lts-5.2
  extra-dep: true
  subdirs:
    - haskoin-core

# haskoin dependencies
extra-deps:
- secp256k1-0.4.4
- murmur3-1.0.1
- pbkdf-1.1.1.1

flags: {}

extra-package-dbs: []

system-ghc: false