resolver: lts-7.1

packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/haskoin.git
    commit: c906ba45d4d797132c42234f80abbf174e07f42e
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet

# Haskoin dependencies
extra-deps:
- haskoin-core-0.4.0
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
